CREATE TABLE IF NOT EXISTS user_info (
    userid NUMERIC,
    commands_done NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_profile (
    userid NUMERIC NOT NULL,
    name VARCHAR(512) UNIQUE NOT NULL,
    multiplier NUMERIC NOT NULL DEFAULT 1,
    inventory VARCHAR(512),
    balance NUMERIC NOT NULL DEFAULT 0,
    enemies_killed NUMERIC NOT NULL DEFAULT 0,
    xp NUMERIC NOT NULL DEFAULT 0,
    creation_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS guild_prefixes (
    guild_id NUMERIC NOT NULL,
    prefix VARCHAR(512) NOT NULL
);
    
